import Link from "next/link";
import { AtSign } from "lucide-react";

export const metadata = {
  title: "Privacy Policy — ThreadLens",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="border-b">
        <div className="mx-auto max-w-3xl w-full flex items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary text-primary-foreground">
              <AtSign className="h-4 w-4" />
            </div>
            <span className="font-semibold">ThreadLens</span>
          </Link>
        </div>
      </header>

      <main className="flex-1">
        <article className="mx-auto max-w-3xl w-full px-6 py-12 space-y-6 text-sm leading-relaxed">
          <header className="space-y-2">
            <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
            <p className="text-muted-foreground">Effective date: April 20, 2026</p>
          </header>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">1. About ThreadLens</h2>
            <p>
              ThreadLens (&quot;we&quot;, &quot;us&quot;, &quot;the service&quot;) is an analytics
              application for personal Threads accounts. We pull public data and insights from
              Threads accounts that you voluntarily connect via Meta&apos;s official OAuth flow,
              and present them in a dashboard alongside AI-generated analysis.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">2. Data We Collect</h2>
            <p>When you register and connect a Threads account, we store:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                <strong>ThreadLens account:</strong> email address and password (hashed with
                bcrypt — we never store passwords in plain text).
              </li>
              <li>
                <strong>Threads profile:</strong> Threads user ID, username, display name, and
                profile picture URL.
              </li>
              <li>
                <strong>Threads access token:</strong> encrypted with AES-256-GCM before storage.
                The token is used solely to call the Threads API on your behalf.
              </li>
              <li>
                <strong>Post content:</strong> text, media URL, permalink, timestamp, and media
                type from posts on your Threads account.
              </li>
              <li>
                <strong>Insights:</strong> per-post counts of views, likes, replies, reposts,
                quotes, shares, plus account-level metrics such as follower count.
              </li>
              <li>
                <strong>AI analysis output:</strong> the text generated by the LLM whenever you
                run a performance or pattern analysis.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">3. How We Use the Data</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To render your Threads analytics dashboard.</li>
              <li>To send post metadata as prompts to an LLM provider (OpenRouter) so it can produce analysis.</li>
              <li>To store analysis history so you can review it later.</li>
              <li>To maintain the connection (refresh access tokens) for as long as your Threads account is linked.</li>
            </ul>
            <p>
              We <strong>do not</strong> sell your data, use it for advertising, or share it with
              any third parties beyond the technical processors listed below.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">4. Third-Party Processors</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Supabase</strong> — database where all data is stored.</li>
              <li><strong>Vercel</strong> — application hosting.</li>
              <li><strong>Meta / Threads Graph API</strong> — source of Threads data (you authorize access through OAuth).</li>
              <li>
                <strong>OpenRouter and the chosen LLM provider</strong> — process analysis prompts. Post content (text and metrics) is sent to the LLM provider when you trigger an analysis.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">5. Storage and Security</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Threads access tokens are encrypted before being stored.</li>
              <li>Admin passwords are hashed with bcrypt at cost 12.</li>
              <li>Database access is server-side only, using a service role.</li>
              <li>Login sessions use httpOnly cookies signed as JWTs.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">6. Your Rights &amp; Data Deletion</h2>
            <p>You can remove your data at any time:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                <strong>Disconnect a Threads account</strong> from the{" "}
                <Link href="/settings" className="underline">Settings</Link> page — all posts,
                insights, and analysis history for that account will be permanently deleted.
              </li>
              <li>
                <strong>Delete your ThreadLens account</strong> — email us (address below) with
                the subject &quot;Delete account&quot;. Data will be removed within 7 days.
              </li>
              <li>
                <strong>Requests from Meta:</strong> if you revoke the app&apos;s permission from
                your Threads settings, Meta sends a signed request to our Data Deletion Callback
                endpoint, and we automatically delete the corresponding data.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">7. Cookies</h2>
            <p>We use only essential cookies:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><code>threadlens_session</code> — login session (httpOnly, signed JWT).</li>
              <li><code>threadlens_active_account</code> — currently selected Threads account in the switcher.</li>
              <li><code>threads_oauth_state</code> — short-lived, used to verify the OAuth state parameter.</li>
            </ul>
            <p>No tracking cookies, no third-party advertising cookies.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">8. Children</h2>
            <p>
              The service is intended for users aged 13 and over, in line with Threads / Meta&apos;s
              terms of service.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">9. Changes to This Policy</h2>
            <p>
              This policy may change from time to time. The &quot;effective date&quot; above will
              be updated whenever it does. Material changes will be communicated by email.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold">10. Contact</h2>
            <p>
              For questions, data access or deletion requests, or privacy concerns:
              <br />
              <a href="mailto:bhskindatabase@gmail.com" className="underline">bhskindatabase@gmail.com</a>
            </p>
          </section>
        </article>
      </main>

      <footer className="border-t">
        <div className="mx-auto max-w-3xl w-full px-6 py-6 text-xs text-muted-foreground flex items-center justify-between">
          <Link href="/" className="hover:text-foreground">← Back to home</Link>
          <span>© {new Date().getFullYear()} ThreadLens</span>
        </div>
      </footer>
    </div>
  );
}
